#[derive(Debug, Clone, Copy)]
pub enum AutoComplete {
    Off,
    On,
    Name,
    HonorificPrefix,
    GivenName,
    AdditionalName,
    FamilyName,
    HonorificSuffix,
    NickName,
    EMail,
    UserName,
    NewPassword,
    CurrentPassword,
    OneTimeCode,
    OrganizationTitle,
    Organization,
    StreetAddress,
    AddressLine1,
    AddressLine2,
    AddressLine3,
    AddressLevel1,
    AddressLevel2,
    AddressLevel3,
    AddressLevel4,
    Country,
    CountryName,
    PostalCode,
    CCName,
    CCGivenName,
    CCAdditionalName,
    CCFamilyName,
    CCNumber,
    CCExp,
    CCExpMonth,
    CCExpYear,
    CCCsc,
    CCType,
    TransactionCurrency,
    TransactionAmount,
    Language,
    BirthDate,
    BirthDay,
    BirthMonth,
    BirthYear,
    Sex,
    Tel,
    TelCountryCode,
    TelNational,
    TelAreaCode,
    TelLocal,
    TelExtension,
    Impp,
    Url,
    Photo,
}

impl AutoComplete {
    pub fn to_static_str(&self) -> &'static str {
        use AutoComplete::*;
        match self {
            Off => "off",
            On => "on",
            Name => "name",
            HonorificPrefix => "honorific-prefix",
            GivenName => "given-name",
            AdditionalName => "additional-name",
            FamilyName => "family-name",
            HonorificSuffix => "honorific-suffix",
            NickName => "nickname",
            EMail => "email",
            UserName => "username",
            NewPassword => "new-password",
            CurrentPassword => "current-password",
            OneTimeCode => "one-time-code",
            OrganizationTitle => "organization-title",
            Organization => "organization",
            StreetAddress => "street-address",
            AddressLine1 => "address-line1",
            AddressLine2 => "address-line2",
            AddressLine3 => "address-line3",
            AddressLevel1 => "address-level1",
            AddressLevel2 => "address-level2",
            AddressLevel3 => "address-level3",
            AddressLevel4 => "address-level4",
            Country => "country",
            CountryName => "country-name",
            PostalCode => "postal-code",
            CCName => "cc-name",
            CCGivenName => "cc-given-name",
            CCAdditionalName => "cc-additional-name",
            CCFamilyName => "cc-family-name",
            CCNumber => "cc-number",
            CCExp => "cc-exp",
            CCExpMonth => "cc-exp-month",
            CCExpYear => "cc-exp-year",
            CCCsc => "cc-csc",
            CCType => "cc-type",
            TransactionCurrency => "transaction-currency",
            TransactionAmount => "transaction-amount",
            Language => "language",
            BirthDate => "bday",
            BirthDay => "bday-day",
            BirthMonth => "bday-month",
            BirthYear => "bday-year",
            Sex => "sex",
            Tel => "tel",
            TelCountryCode => "tel-country-code",
            TelNational => "tel-national",
            TelAreaCode => "tel-area-code",
            TelLocal => "tel-local",
            TelExtension => "tel-extension",
            Impp => "impp",
            Url => "url",
            Photo => "photo",
        }
    }
}